---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loxi-agent
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loxi-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - crd.loxilight.io
    resources:
      - tunnelinfos
      - veths
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loxi-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loxi-agent
subjects:
  - kind: ServiceAccount
    name: loxi-agent
    namespace: kube-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: veths.crd.loxilight.io
  #annotations:
    #api-approved.kubernetes.io: "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: crd.loxilight.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeName:
                  type: string
                name:
                  type: string
                peerName:
                  type: string
                connectedPod:
                  type: object
                  properties:
                    containerID:
                      type: string
                    containerIPs:
                      type: array
                      items:
                        type: string
                    netNS:
                      type: string
  names:
    kind: Veth
    singular: veth
    plural: veths
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tunnelinfos.crd.loxilight.io
spec:
  group: crd.loxilight.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required:
                - nodeName
              type: object
              properties:
                nodeName:
                  type: string
                localIP:
                  type: string
                tunnelIP:
                  type: string
                podCIDR:
                  type: string
                nodeIP:
                  type: string
  names:
    kind: TunnelInfo
    singular: tunnelinfo
    plural: tunnelinfos
  scope: Cluster
